import type { ThemeId } from "@/types";

export interface ThemeDefinition {
  id: ThemeId;
  name: string;
  description: string;
  cssVars: Record<string, string>;
}

export const themes: Record<ThemeId, ThemeDefinition> = {
  "zen-dark": {
    id: "zen-dark",
    name: "Zen Dark",
    description: "Japanese-inspired warm tones, matcha accents, calm by default",
    cssVars: {
      "--bg-primary": "#1a1a1a",
      "--bg-secondary": "#232322",
      "--bg-tertiary": "#2c2c2a",
      "--bg-surface": "#363633",
      "--text-primary": "#e8e4de",
      "--text-secondary": "rgba(232, 228, 222, 0.7)",
      "--text-tertiary": "rgba(232, 228, 222, 0.45)",
      "--border-color": "rgba(232, 228, 222, 0.06)",
      "--border-color-strong": "rgba(232, 228, 222, 0.12)",
      "--accent-start": "#c4786a",
      "--accent-end": "#d4a07a",
      "--font-primary": "'Inter', sans-serif",
      "--font-size-base": "14px",
      "--line-height-base": "1.6",
      "--letter-spacing": "normal",
      "--word-spacing": "normal",
      "--radius-sm": "8px",
      "--radius-md": "12px",
      "--radius-lg": "16px",
      "--border-width": "1px",
      "--event-blue-bg": "rgba(80, 140, 180, 0.15)",
      "--event-blue-border": "#5a9ab5",
      "--event-blue-text": "#8ec4db",
      "--event-red-bg": "rgba(195, 100, 90, 0.15)",
      "--event-red-border": "#c46a5e",
      "--event-red-text": "#e0a098",
      "--event-green-bg": "rgba(100, 170, 100, 0.15)",
      "--event-green-border": "#6aaa6a",
      "--event-green-text": "#9dd49d",
      "--event-purple-bg": "rgba(150, 115, 180, 0.15)",
      "--event-purple-border": "#9672b0",
      "--event-purple-text": "#bfa4d4",
      "--event-amber-bg": "rgba(200, 165, 80, 0.15)",
      "--event-amber-border": "#c8a550",
      "--event-amber-text": "#e0cc8a",
    },
  },
  "morgen-dark": {
    id: "morgen-dark",
    name: "Morgen Dark",
    description: "Deep navy, pro calendar look with coral-gold accents",
    cssVars: {
      "--bg-primary": "#1c1d26",
      "--bg-secondary": "#252630",
      "--bg-tertiary": "#2e3040",
      "--bg-surface": "#353748",
      "--text-primary": "#ffffff",
      "--text-secondary": "rgba(255, 255, 255, 0.7)",
      "--text-tertiary": "rgba(255, 255, 255, 0.5)",
      "--border-color": "rgba(255, 255, 255, 0.08)",
      "--border-color-strong": "rgba(255, 255, 255, 0.15)",
      "--accent-start": "#FF8295",
      "--accent-end": "#F3C26A",
      "--font-primary": "'Inter', sans-serif",
      "--font-size-base": "14px",
      "--line-height-base": "1.5",
      "--letter-spacing": "normal",
      "--word-spacing": "normal",
      "--radius-sm": "6px",
      "--radius-md": "10px",
      "--radius-lg": "14px",
      "--border-width": "1px",
      "--event-blue-bg": "rgba(59, 130, 246, 0.2)",
      "--event-blue-border": "#3b82f6",
      "--event-blue-text": "#93c5fd",
      "--event-red-bg": "rgba(239, 68, 68, 0.2)",
      "--event-red-border": "#ef4444",
      "--event-red-text": "#fca5a5",
      "--event-green-bg": "rgba(34, 197, 94, 0.2)",
      "--event-green-border": "#22c55e",
      "--event-green-text": "#86efac",
      "--event-purple-bg": "rgba(168, 85, 247, 0.2)",
      "--event-purple-border": "#a855f7",
      "--event-purple-text": "#d8b4fe",
      "--event-amber-bg": "rgba(245, 158, 11, 0.2)",
      "--event-amber-border": "#f59e0b",
      "--event-amber-text": "#fcd34d",
    },
  },
  "morgen-light": {
    id: "morgen-light",
    name: "Morgen Light",
    description: "Clean white, airy feel with muted accents",
    cssVars: {
      "--bg-primary": "#f8f9fa",
      "--bg-secondary": "#ffffff",
      "--bg-tertiary": "#f0f1f3",
      "--bg-surface": "#e9eaed",
      "--text-primary": "#1a1a2e",
      "--text-secondary": "rgba(26, 26, 46, 0.7)",
      "--text-tertiary": "rgba(26, 26, 46, 0.5)",
      "--border-color": "rgba(0, 0, 0, 0.08)",
      "--border-color-strong": "rgba(0, 0, 0, 0.15)",
      "--accent-start": "#e06070",
      "--accent-end": "#d4a84a",
      "--font-primary": "'Inter', sans-serif",
      "--font-size-base": "14px",
      "--line-height-base": "1.5",
      "--letter-spacing": "normal",
      "--word-spacing": "normal",
      "--radius-sm": "6px",
      "--radius-md": "10px",
      "--radius-lg": "14px",
      "--border-width": "1px",
      "--event-blue-bg": "rgba(59, 130, 246, 0.1)",
      "--event-blue-border": "#3b82f6",
      "--event-blue-text": "#1d4ed8",
      "--event-red-bg": "rgba(239, 68, 68, 0.1)",
      "--event-red-border": "#ef4444",
      "--event-red-text": "#b91c1c",
      "--event-green-bg": "rgba(34, 197, 94, 0.1)",
      "--event-green-border": "#22c55e",
      "--event-green-text": "#15803d",
      "--event-purple-bg": "rgba(168, 85, 247, 0.1)",
      "--event-purple-border": "#a855f7",
      "--event-purple-text": "#7e22ce",
      "--event-amber-bg": "rgba(245, 158, 11, 0.1)",
      "--event-amber-border": "#f59e0b",
      "--event-amber-text": "#b45309",
    },
  },
  dyslexia: {
    id: "dyslexia",
    name: "Dyslexia-Friendly",
    description: "OpenDyslexic font, cream background, large text, extra spacing",
    cssVars: {
      "--bg-primary": "#fdf6e3",
      "--bg-secondary": "#fef9ef",
      "--bg-tertiary": "#f5edd6",
      "--bg-surface": "#ece4cd",
      "--text-primary": "#2d2d2d",
      "--text-secondary": "rgba(45, 45, 45, 0.75)",
      "--text-tertiary": "rgba(45, 45, 45, 0.55)",
      "--border-color": "rgba(45, 45, 45, 0.15)",
      "--border-color-strong": "rgba(45, 45, 45, 0.25)",
      "--accent-start": "#c44d34",
      "--accent-end": "#b8860b",
      "--font-primary": "'OpenDyslexic', 'Comic Sans MS', cursive, sans-serif",
      "--font-size-base": "18px",
      "--line-height-base": "1.8",
      "--letter-spacing": "0.05em",
      "--word-spacing": "0.15em",
      "--radius-sm": "8px",
      "--radius-md": "12px",
      "--radius-lg": "16px",
      "--border-width": "2px",
      "--event-blue-bg": "rgba(59, 130, 246, 0.15)",
      "--event-blue-border": "#2563eb",
      "--event-blue-text": "#1e40af",
      "--event-red-bg": "rgba(239, 68, 68, 0.15)",
      "--event-red-border": "#dc2626",
      "--event-red-text": "#991b1b",
      "--event-green-bg": "rgba(34, 197, 94, 0.15)",
      "--event-green-border": "#16a34a",
      "--event-green-text": "#166534",
      "--event-purple-bg": "rgba(168, 85, 247, 0.15)",
      "--event-purple-border": "#9333ea",
      "--event-purple-text": "#6b21a8",
      "--event-amber-bg": "rgba(245, 158, 11, 0.15)",
      "--event-amber-border": "#d97706",
      "--event-amber-text": "#92400e",
    },
  },
  "high-contrast": {
    id: "high-contrast",
    name: "High Contrast",
    description: "Pure black/white, WCAG AAA, bold borders, maximum readability",
    cssVars: {
      "--bg-primary": "#000000",
      "--bg-secondary": "#0a0a0a",
      "--bg-tertiary": "#1a1a1a",
      "--bg-surface": "#2a2a2a",
      "--text-primary": "#ffffff",
      "--text-secondary": "#e0e0e0",
      "--text-tertiary": "#b0b0b0",
      "--border-color": "rgba(255, 255, 255, 0.3)",
      "--border-color-strong": "rgba(255, 255, 255, 0.6)",
      "--accent-start": "#ff6b6b",
      "--accent-end": "#ffd93d",
      "--font-primary": "system-ui, -apple-system, sans-serif",
      "--font-size-base": "16px",
      "--line-height-base": "1.6",
      "--letter-spacing": "0.01em",
      "--word-spacing": "normal",
      "--radius-sm": "4px",
      "--radius-md": "6px",
      "--radius-lg": "8px",
      "--border-width": "2px",
      "--event-blue-bg": "rgba(59, 130, 246, 0.3)",
      "--event-blue-border": "#60a5fa",
      "--event-blue-text": "#93c5fd",
      "--event-red-bg": "rgba(239, 68, 68, 0.3)",
      "--event-red-border": "#f87171",
      "--event-red-text": "#fca5a5",
      "--event-green-bg": "rgba(34, 197, 94, 0.3)",
      "--event-green-border": "#4ade80",
      "--event-green-text": "#86efac",
      "--event-purple-bg": "rgba(168, 85, 247, 0.3)",
      "--event-purple-border": "#c084fc",
      "--event-purple-text": "#d8b4fe",
      "--event-amber-bg": "rgba(245, 158, 11, 0.3)",
      "--event-amber-border": "#fbbf24",
      "--event-amber-text": "#fcd34d",
    },
  },
  pastel: {
    id: "pastel",
    name: "Pastel / Soft",
    description: "Lavender tints, rounded corners, playful and friendly",
    cssVars: {
      "--bg-primary": "#f0e6ff",
      "--bg-secondary": "#f8f4ff",
      "--bg-tertiary": "#e8daf5",
      "--bg-surface": "#ddd0ee",
      "--text-primary": "#2d1b4e",
      "--text-secondary": "rgba(45, 27, 78, 0.7)",
      "--text-tertiary": "rgba(45, 27, 78, 0.5)",
      "--border-color": "rgba(45, 27, 78, 0.1)",
      "--border-color-strong": "rgba(45, 27, 78, 0.2)",
      "--accent-start": "#ff9eb5",
      "--accent-end": "#ffcc80",
      "--font-primary": "'Poppins', 'Nunito', sans-serif",
      "--font-size-base": "15px",
      "--line-height-base": "1.6",
      "--letter-spacing": "0.01em",
      "--word-spacing": "normal",
      "--radius-sm": "12px",
      "--radius-md": "16px",
      "--radius-lg": "20px",
      "--border-width": "1px",
      "--event-blue-bg": "rgba(147, 197, 253, 0.4)",
      "--event-blue-border": "#93c5fd",
      "--event-blue-text": "#1e40af",
      "--event-red-bg": "rgba(252, 165, 165, 0.4)",
      "--event-red-border": "#fca5a5",
      "--event-red-text": "#991b1b",
      "--event-green-bg": "rgba(134, 239, 172, 0.4)",
      "--event-green-border": "#86efac",
      "--event-green-text": "#166534",
      "--event-purple-bg": "rgba(216, 180, 254, 0.4)",
      "--event-purple-border": "#d8b4fe",
      "--event-purple-text": "#6b21a8",
      "--event-amber-bg": "rgba(252, 211, 77, 0.4)",
      "--event-amber-border": "#fcd34d",
      "--event-amber-text": "#92400e",
    },
  },
};

export function applyTheme(themeId: ThemeId): void {
  const theme = themes[themeId];
  if (!theme) return;
  const root = document.documentElement;
  for (const [key, value] of Object.entries(theme.cssVars)) {
    root.style.setProperty(key, value);
  }
}
